import {useState} from "react";
import {scopes,inspectScope,visibleScopes} from "./logic.mjs";
const words:Record<string,[string,string]>={
approval_review:["Approval state needs review.","批件状态需要复核。"],agreement_unknown:["Agreement status is unknown; absence is not established.","协议状态未知，不能断言没有协议。"],signature_not_confirmed:["A draft/expired document does not confirm an effective signed agreement.","草稿或已失效文件不能确认有效双签协议。"],signed_evidence_missing:["The signed flag lacks confirmed signature evidence.","已签状态缺少已确认的签署证据。"],owner_unassigned:["Responsibility owner is not assigned.","责任负责人尚未分配。"],follow_up_due:["The illustrative follow-up deadline is due.","示例跟进期限已到。"],invalid_sale_date:["The fictional first-sale date is invalid.","合成首次销售日期无效。"]
};
export default function Demo({language}:{language:"en"|"zh"}){
 const zh=language==="zh";const [region,setRegion]=useState("all");const [view,setView]=useState("all");const [selected,setSelected]=useState(scopes[0].id);const [evidence,setEvidence]=useState(true);const [reviewed,setReviewed]=useState<string[]>([]);
 const rows:typeof scopes=visibleScopes(scopes,region,view);const current=rows.find(r=>r.id===selected)||rows[0];
 const result=current?inspectScope({...current,signatureEvidence:current.signatureEvidence&&evidence}):null;
 const changeSelection=(id:string)=>{setSelected(id);setEvidence(true)};
 const chooseRegion=(value:string)=>{setRegion(value);setEvidence(true)};
 const chooseView=(value:string)=>{setView(value);setEvidence(true)};
 return <><h2>{zh?"虚构国家—产品治理矩阵":"Fictional country–product governance matrix"}</h2><p className="small">{zh?"示例基准日：2026-06-01。销售前 3 个日历月仅为可解释的演示跟进规则，不是法规期限。":"Demo as-of date: 2026-06-01. Three calendar months before first sale is an illustrative follow-up rule, not a regulatory deadline."}</p><div className="two-fields" style={{marginBottom:22}}><label>{zh?"虚构地区":"Fictional region"}<select data-testid="region" value={region} onChange={e=>chooseRegion(e.target.value)}><option value="all">{zh?"全部":"All"}</option><option>SYN-REGION-A</option><option>SYN-REGION-B</option></select></label><label>{zh?"展示视图（非权限）":"Display view (not authorization)"}<select data-testid="view" value={view} onChange={e=>chooseView(e.target.value)}><option value="all">{zh?"全部范围":"All scopes"}</option><option value="review">{zh?"需要复核":"Needs review"}</option></select></label></div><div className="grid"><div className="panel"><h3>{zh?"合成范围":"Synthetic scopes"}</h3><div className="table-scroll"><table><thead><tr><th>{zh?"产品 / 地区":"Product / region"}</th><th>{zh?"注册 / 协议":"Approval / agreement"}</th><th>{zh?"检查":"Inspect"}</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><code>{row.product}</code><br/>{row.region}</td><td>{row.approval}<br/>{row.agreement}</td><td><button data-testid={row.id} onClick={()=>changeSelection(row.id)}>{zh?"查看":"Open"}</button></td></tr>)}</tbody></table></div><p className="small" style={{marginTop:16}}>{zh?"表格是公开合成资料；视图过滤不实现服务器权限控制。":"The table is public synthetic material. View filtering implements no server authorization."}</p></div><div className="panel" aria-live="polite">{current&&result?<><h3>{current.id}</h3><span data-testid="status" className={"badge "+(result.state==="review_required"?"warn":"ok")}>{result.state==="review_required"?(zh?"需要复核（演示）":"Needs review · demo"):(zh?"材料可供复核（演示）":"Ready for review · demo")}</span><p>{zh?"合成文件":"Synthetic document"}: <code>{current.document}</code></p><p>{zh?"责任角色":"Responsibility role"}: {current.owner||"SYN-UNASSIGNED"}</p><p>{zh?"示例跟进期限":"Illustrative follow-up date"}: {result.due||(zh?"尚未确定":"Unknown")}</p><label className="inline"><input data-testid="signature-evidence" type="checkbox" checked={evidence} onChange={e=>setEvidence(e.target.checked)}/>{zh?"本示例保留签署证据字段":"Keep signature-evidence field in this example"}</label><ul>{result.reasons.map(key=><li key={key}>{words[key]?.[zh?1:0]||key}</li>)}</ul><div className="review"><button data-testid="review" className="primary" onClick={()=>setReviewed(prev=>[...prev,current.id])}>{zh?"模拟添加跟进":"Add demo follow-up"}</button></div><p data-testid="activity" className="small">{zh?"当前页面的合成跟进记录":"Synthetic follow-up actions in this page"}: {reviewed.length}</p><p className="small">{zh?"本地示例操作不会确认签署、改变注册状态或生成真实审计记录。":"Local demo actions do not confirm signatures, change registrations or create a real audit record."}</p></>:<p className="empty">{zh?"当前过滤条件无示例。":"No examples for these filters."}</p>}</div></div></>;
}
