import React, { useState } from "react";
import { createRoot } from "react-dom/client";
import Demo from "./Demo";
import "./styles.css";
function App(){
 const [language,setLanguage]=useState<"en"|"zh">("en");
 const zh=language==="zh";
 React.useEffect(()=>{document.documentElement.lang=zh?"zh-CN":"en";},[zh]);
 return <><header><div className="brand"><span>EVIDENCE LAB</span> / SYNTHETIC SHOWCASE</div><button aria-label={zh?"Switch to English":"切换中文"} onClick={()=>setLanguage(zh?"en":"zh")}>{zh?"English":"中文"}</button></header><main><div className="eyebrow">{zh?"独立实现 · 全合成数据":"Independent implementation · Synthetic data only"}</div><section className="hero"><div><h1>{zh?"International PV · 数据治理":"International PV · Data governance"}</h1><p className="lede">{zh?"连接注册状态、协议责任与跟进证据。":"Link registrations, agreements and follow-up evidence."}</p></div><div className="scope"><strong>{zh?"公开展示范围":"Public scope"}</strong><p>{zh?"本页面只使用完全虚构的示例，展示流程和方法。无真实业务结果、公司源代码、账号、接口调用或文件上传。":"Fabricated examples illustrate workflow and methods. No operational results, company implementation, accounts, API calls or file uploads."}</p></div></section><section className="steps" aria-label={zh?"流程":"Workflow"}><div className="step"><small>01</small>Country-product scope</div><div className="step"><small>02</small>Agreement evidence</div><div className="step"><small>03</small>Responsibility map</div><div className="step"><small>04</small>Follow-up review</div></section><section className="workspace"><Demo language={language}/></section><div className="notice">{zh?"所有屏幕数值、编号、名称和日期均为合成示例。浏览器中的过滤、复核和导出是演示功能，不提供生产权限、真实审核记录或监管结论。":"All displayed counts, identifiers, labels and dates are fabricated. Browser filtering, review and export illustrate interactions; they provide no production authorization, genuine audit trail or regulatory conclusion."}</div><footer><span>International PV · Data governance · Portfolio methods and workflow</span><a href="https://github.com/Unravelreggie/international-pv-governance-showcase" target="_blank" rel="noreferrer">{zh?"项目源码与说明":"Repository and documentation"} ↗</a></footer></main></>;
}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
